### ISSUE TITLE
switching git branches resets custom icons

### ISSUE THREAD

**Issue by YehudaK** [Unity-Technologies/NotificationsSamples#10]
Every time I switch git branches, all custom icons set in **Edit->Project Settings->Mobile Notification Settings** gets reset and I have to create icons again. Is there any specific file in Unity project which I should track to prevent this?

Thanks

**Comment by YehudaK** [comment]
The problem is that all changes are successfully saved in /Assets/Editor/com.unity.mobile.notifications/NotificationSettings.asset and later merged to release branch BUT once I start Unity, it removes those lines bellow:

```
  AndroidNotificationEditorSettingsValues:
    keys:
    - UnityNotificationAndroidRescheduleOnDeviceRestart
    values:
    - False
  TrackedResourceAssets:
  - Id: icon_fully_recovered
    Type: 0
    Asset: {fileID: 2800000, guid: 7854c247df753814fbab6838b04909ac, type: 3}
  - Id: icon_continue_play
    Type: 0
    Asset: {fileID: 2800000, guid: b4d30efc27d2f45449a5d936773e0573, type: 3}
  - Id: icon_app
    Type: 1
    Asset: {fileID: 2800000, guid: 3615aca4454f2454e8d35194b8b9a7aa, type: 3}
    keys: []
    values: []
```

and replaces them with this:

```
  AndroidNotificationEditorSettingsValues:
    keys: []
    values: []
  TrackedResourceAssets: []
```
